# Data transformation


```{r}
library(tidyr)
library(tidyverse)
library(dplyr)
library(lubridate)
library(chron)
DATA <- read.csv("NYPD_Complaint_Data_Current__Year_To_Date_.csv",na.strings = "")
str(DATA)
DATA <-DATA[!is.na(DATA$CMPLNT_FR_DT), ]
DATA$CMPLNT_FR_DT <-as.Date(DATA$CMPLNT_FR_DT,format = "%m/%d/%Y")

for(i in 1:nrow(DATA)){
  if(year(DATA[i,4]) =='1018'){year(DATA[i,4]) <-2018}
  if(year(DATA[i,4]) =='1019'){year(DATA[i,4]) <-2019}
  if(year(DATA[i,4]) =='1029'){year(DATA[i,4]) <-2019}
}

DATA$CMPLNT_FR_TM <-as.character(DATA$CMPLNT_FR_TM)
DATA$CMPLNT_FR_TM <-chron(times=DATA$CMPLNT_FR_TM)

df <- DATA %>%
  filter(CMPLNT_FR_DT >=as.Date('2018-01-01'))
```

```{r}
offense <- c('ANTICIPATORY OFFENSES', "OFF. AGNST PUB ORD SENSBLTY &", "OFFENSES AGAINST MARRIAGE UNCL", "OFFENSES AGAINST PUBLIC ADMINI", "OFFENSES AGAINST PUBLIC SAFETY", "OFFENSES AGAINST THE PERSON", "OFFENSES INVOLVING FRAUD", "OFFENSES RELATED TO CHILDREN", "OTHER OFFENSES RELATED TO THEF")
assault <- c('ASSAULT 3 & RELATED OFFENSES', 'FELONY ASSAULT', "HARRASSMENT 2")
burglary <- c('BURGLARY', "BURGLAR'S TOOLS", "CRIMINAL TRESPASS")
drug <- c("DANGEROUS DRUGS")
weapon <- c("DANGEROUS WEAPONS", "UNLAWFUL POSS. WEAP. ON SCHOOL" )
rape <- c("FELONY SEX CRIMES", "RAPE", "SEX CRIMES")
fraud <- c("FRAUDS", "FORGERY", "FRAUDULENT ACCOSTING", "THEFT-FRAUD")
thief <- c("GRAND LARCENY", "GRAND LARCENY OF MOTOR VEHICLE", "OTHER OFFENSES RELATED TO THEF", "PETIT LARCENY", "PETIT LARCENY OF MOTOR VEHICLE", "POSSESSION OF STOLEN PROPERTY", "THEFT OF SERVICES")
murder <- c("MURDER & NON-NEGL. MANSLAUGHTER")
kidnapping <- c("KIDNAPPING", "KIDNAPPING & RELATED OFFENSES", "KIDNAPPING AND RELATED OFFENSES")

picked <- c('ROBBERY', "OFFENSE", "ARSON", "BURGLARY", "DRUG", "WEAPON", "RAPE", "FRAUD", "THIEF", "MURDER", "KIDNAPPING")
df$OFNS_DESC <- as.character(df$OFNS_DESC)
df <- df %>% mutate(OFNS_DESC = ifelse(OFNS_DESC %in% offense, "OFFENSE", OFNS_DESC))
df <- df %>% mutate(OFNS_DESC = ifelse(OFNS_DESC %in% assault, "ASSAULT", OFNS_DESC))
df <- df %>% mutate(OFNS_DESC = ifelse(OFNS_DESC %in% drug, "DRUG", OFNS_DESC))
df <- df %>% mutate(OFNS_DESC = ifelse(OFNS_DESC %in% weapon, "WEAPON", OFNS_DESC))
df <- df %>% mutate(OFNS_DESC = ifelse(OFNS_DESC %in% rape, "RAPE", OFNS_DESC))
df <- df %>% mutate(OFNS_DESC = ifelse(OFNS_DESC %in% fraud, "FRAUD", OFNS_DESC))
df <- df %>% mutate(OFNS_DESC = ifelse(OFNS_DESC %in% thief, "THIEF", OFNS_DESC))
df <- df %>% mutate(OFNS_DESC = ifelse(OFNS_DESC %in% murder, "MURDER", OFNS_DESC))
df <- df %>% mutate(OFNS_DESC = ifelse(OFNS_DESC %in% kidnapping, "KIDNAPPING", OFNS_DESC))

df <- df %>% mutate(OFNS_DESC = ifelse(OFNS_DESC %in% picked, OFNS_DESC, NA)) %>% drop_na(OFNS_DESC)
```

```{r}
cols <- c('BORO_NM', 'CMPLNT_FR_DT','CMPLNT_FR_TM','OFNS_DESC', 'SUSP_AGE_GROUP', 'PREM_TYP_DESC', 'SUSP_AGE_GROUP', 'SUSP_SEX', 'SUSP_RACE', 'VIC_AGE_GROUP', 'VIC_RACE', 'VIC_SEX', 'Latitude', 'Longitude')
df_select <- df[, cols]
```

```{r}
picked_time <- c("07am - 11am", "15pm - 19pm", "19pm - 23pm")
crime_color <- c("#7851a9", "#800020", "#ef5927", "#0079c1", "#dac751", "#133a30")

df_select <- df_select %>% drop_na(BORO_NM)
df_select <- df_select %>% mutate(timerange = CMPLNT_FR_TM)
df_select <- df_select %>% mutate(timerange = ifelse(CMPLNT_FR_TM >= chron(times="07:00:00") 
                                                & CMPLNT_FR_TM <= chron(times="11:00:00"),
                                                "07am - 11am", timerange) )
df_select <- df_select %>% mutate(timerange = ifelse(CMPLNT_FR_TM >= chron(times="15:00:00") 
                                                & CMPLNT_FR_TM <= chron(times="19:00:00"),
                                                "15pm - 19pm", timerange) )
df_select <- df_select %>% mutate(timerange = ifelse(CMPLNT_FR_TM >= chron(times="19:00:00") 
                                                & CMPLNT_FR_TM <= chron(times="23:00:00"),
                                                "19pm - 23pm", timerange) )

df_select <- df_select %>% mutate(color = timerange)
df_select <- df_select %>% mutate( color = ifelse(timerange == picked_time[1], "red", color) )
df_select <- df_select %>% mutate( color = ifelse(timerange == picked_time[2], "green", color) )
df_select <- df_select %>% mutate( color = ifelse(timerange == picked_time[3], "blue", color) )

df_select <- df_select %>% mutate(crimecolor = OFNS_DESC)
for(i in 1:length(dangerous)){
  df_select <- df_select %>% mutate( crimecolor = ifelse(OFNS_DESC == dangerous[i], crime_color[i], crimecolor) )   
}

df_select <- df_select %>% mutate(timerange = ifelse(timerange %in% picked_time, timerange, NA)) %>% drop_na(timerange)
```

```{r}
dangerous <-c('BURGLARY','OFFENSE','RAPE','ROBBERY','THIEF','WEAPON')
df_select <- df_select %>% mutate(OFNS_DESC = ifelse(OFNS_DESC %in% dangerous, OFNS_DESC, NA)) %>% drop_na(OFNS_DESC)
df_select <- drop_na(df_select, BORO_NM)
```
