# Conclusion

## Borough We Recommend
Base on concerning about crime type, crime time, and victim age group, the three safer boroughs should be Manhattan, Queens, Staten Island. Although Manhattan has a higher total crime rate than Brooklyn and Bronx, the major crime types in Manhattan actually are offense and theft which doesn't directly endanger our life. For Brooklyn and Bronx, these two boroughs have the highest and second highest crime rate in the most severe crime types(rape, robbery, weapon, burglary). For Staten Island, if we consider commute time, it may not a good choice for the student who attends university in Manhattan. Therefore, we recommend full-time students to live in Manhattan and Queens.

## Specific Address for Selected Borough
For the more detailed address, we find out two specific addresses from our interactive graph base on our schedule and rank. The first place we recommend is a long island city in Queens. In the interactive graph, there are only 4 crimes(three theft and one offense) happen near that place and even no recorded crime at 7 am - 11 am. These four crimes are not considered a severe crime in our criteria. The second place is Roosevelt Island which has only two recorded theft and has no recorded crime at 7 pm - 11 pm. It should be a good choice for the student who has more courses in the afternoon and evening. For the student who would like to live in Manhattan, Manhattan downtown has lower crime at 7 am - 11 am and 7 pm-11 pm and both midtown and downtown have less severe crime than uptown.

## Limitation
However, safety is not the only criteria for choosing a place to live in. There are some other factors such as commute time and price should also be taken into account. In our research, we only use selected crime rates to select the best place for students. Luckily, the commute time from two addresses we selected to Manhattan is in an acceptable range in our knowledge. Another limitation is that, as we know, a lot of students in Manhattan also consider New Jersey as a good place to living in because of its acceptable commute time and lower price, while the crime record of the place near New York City has not included into our dataset. For future research, we should include the crime record of the area in New Jersy that is close to NYC and give other analysis about the rent price and commute time. We believe if we do that, we can find a more suitable place for full-time student to live in.
