--- 
title: "NYC Crime Analysis"
author: "Yichi Zhang, Zelin Li, Huayun Xu, Mingfang Chang"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction



Many full-time students at Columbia, including us, are living off campus currently and may need to find new housing in the next semester or the next year. Among all the considerations while searching available apartments, Most of students care most about the safety of areas surrounding the apartment. However, when googling the crime rate analysis, we found that they are not very instructive, as there are many crime types included that irrelevent to us. Hence the objective of our final project is that based on the crime types we care about, the time periods we go outside, and victim age group of crimes in each borough, finding the relatively safe areas by researching the crime rate of five boroughts, Manhattan, Bronx, Brooklyn, Queens and Staten Island, in New York City. If possible, we would like to find the specific addresses in selected borough which can be regarded as a reference of safety for all students who are finding housing.